---
- name: creating kube master instance
  hosts: localhost 
  connection: local
  vars_files:
  - group_vars/k8_master_vars
  roles:
    - kube-master-create 


- name: configuring master node
  hosts: k8_master
  remote_user: ec2-user
  become: true
  become_method: sudo
  vars_files:
  - group_vars/k8_master_vars 
  roles:
    - kube-master-install

- name: Creating worker nodes
  hosts: localhost
  connection: local
  vars_files:
  - group_vars/k8_master_vars
  roles:
    - worker-node-create

- name: Installing  worker node tools
  hosts: "{{ groups['k8_node'][0] }}" 
  become: true
  become_method: sudo
  vars_files:
  - group_vars/k8_master_vars
  roles:
    - worker-node-install

- name: Installing  worker node tools
  hosts: "{{ groups['k8_node'][1] }}"
  become: true
  become_method: sudo
  vars_files:
  - group_vars/k8_master_vars
  roles:
    - worker-node-install
