---
- name: install the latest version of Docker
  yum:
    name: docker
    state: latest

- name: enabling docker service
  service:
    name: docker
    enabled: yes

- name: Starting docker service
  service:
    name: docker
    state: started

- name: Adding kubernetes repo to yum
  yum_repository:
    name: Kubernetes
    description: Kubernetes
    file: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    mirrorlist: http://mirrorlist.repoforge.org/el7/mirrors-rpmforge
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude: kubelet kubeadm kubectl


- name: installing kubelet kubeadm kubectl
  command: yum install -y kubelet kubeadm kubectl --disableexcludes=Kubernetes

- name: enabling kubelet service
  service:
    name: kubelet
    enabled: yes

#- name: publishing kudeadm output as a fact
#  shell: 'cat {{ files_path }}/kubeadm_init_output | grep  "kubeadm join"'
#  register: __kubeinit_token
#
#- debug:
#    var: __kubeinit_token.stdout
#
#- name: facts
#  set_fact:
#     token: "{{ __kubeinit_token.stdout }}"
#
#- name: adding to Kube master
#  shell: "{{ token }}"

- name: Generate join token
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['k8_master'][0] }}"

- set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

- name: Run kubeadm join
  shell: "{{ kubeadm_join }}"

- pause:
    prompt: "Wait for containers to Pull and install"

